# --- Configurações Básicas do Servidor ---
server.port=8082
spring.application.name=catalogo-service

# --- Banco de Dados NoSQL (MongoDB) ---
spring.data.mongodb.uri=mongodb://admin:admin@localhost:27017/ingressos_db?authSource=admin
spring.data.mongodb.auto-index-creation=true

# --- Cache (Redis) ---
spring.data.redis.host=localhost
spring.data.redis.port=6379

# --- Segurança Zero-Trust (Keycloak JWT) ---
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/ingressos-app

# --- Monitoramento e Healthchecks (Actuator) ---
management.endpoints.web.exposure.include=health, info
management.endpoint.health.show-details=always

# --- Observabilidade e Tracing (Micrometer + Zipkin) ---
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans