# --- Configuracoes Basicas do Servidor ---
server.port=8080
spring.application.name=api-gateway

# --- Configuracoes de CORS Global ---
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:4200
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*

# --- Cache (Redis) ---
spring.data.redis.host=localhost
spring.data.redis.port=6379

# --- Monitoramento e Healthchecks (Actuator) ---
management.endpoints.web.exposure.include=health, info
management.endpoint.health.show-details=always

# --- Resiliencia: Circuit Breaker e Timeout ---
resilience4j.timelimiter.configs.default.timeout-duration=3s
resilience4j.circuitbreaker.configs.default.failure-rate-threshold=50
resilience4j.circuitbreaker.configs.default.wait-duration-in-open-state=10s

# --- Observabilidade e Tracing (Micrometer + Zipkin) ---
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans